credentials:
  usernames:
    admin:
      email: joao.saraiva@treevia.com.br
      logged_in: False
      name: Joao Saraiva
      password: admin123
cookie:
  expiry_days: 1
  key: some_signature_ley
  name: some_cookie_name